version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0

    steps:
      - run: apt update && apt install -yq default-jre # required for Sonar
      - checkout
      - run:
          name: Run Cake script
          command: ./build.sh --target CI
