version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0

    steps:
      - checkout
      - run:
          name: Run Cake script
          command: ./build.sh --target CI
