// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrueLayerSdk.SampleApp.Data;

namespace TrueLayerSdk.SampleApp.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    [Migration("20210425082124_PaymentInit")]
    partial class PaymentInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("TrueLayerSdk.SampleApp.Data.PaymentEntity", b =>
                {
                    b.Property<string>("PaymentEntityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("PaymentEntityId");

                    b.ToTable("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
